#how many seconds combat log lasts
#put time in seconds!
time : 12

#commands the player can't do while combat logged
commands :
  - '/hub'
  - '/lobby'
  - '/spawn'
  - '/home'
  - '/warp'
  - '/tpa'
  - '/back'
